/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyCounterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "entropyOracle"
      | "getCounter"
      | "getEntropyOracle"
      | "getIncrementCount"
      | "increment"
      | "incrementCount"
      | "incrementRequests"
      | "incrementWithEntropy"
      | "initialize"
      | "isInitialized"
      | "requestIncrement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CounterIncremented"
      | "CounterInitialized"
      | "IncrementRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIncrementCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "increment", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "incrementCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "incrementRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementWithEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestIncrement",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCounter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncrementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "increment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incrementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIncrement",
    data: BytesLike
  ): Result;
}

export namespace CounterIncrementedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CounterInitializedEvent {
  export type InputTuple = [initializer: AddressLike];
  export type OutputTuple = [initializer: string];
  export interface OutputObject {
    initializer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IncrementRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyCounter extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyCounter;
  waitForDeployment(): Promise<this>;

  interface: EntropyCounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  getCounter: TypedContractMethod<[], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  getIncrementCount: TypedContractMethod<[], [bigint], "view">;

  increment: TypedContractMethod<[], [void], "nonpayable">;

  incrementCount: TypedContractMethod<[], [bigint], "view">;

  incrementRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  incrementWithEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [encryptedValue: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  requestIncrement: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCounter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIncrementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "increment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "incrementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "incrementRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "incrementWithEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [encryptedValue: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestIncrement"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getEvent(
    key: "CounterIncremented"
  ): TypedContractEvent<
    CounterIncrementedEvent.InputTuple,
    CounterIncrementedEvent.OutputTuple,
    CounterIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "CounterInitialized"
  ): TypedContractEvent<
    CounterInitializedEvent.InputTuple,
    CounterInitializedEvent.OutputTuple,
    CounterInitializedEvent.OutputObject
  >;
  getEvent(
    key: "IncrementRequested"
  ): TypedContractEvent<
    IncrementRequestedEvent.InputTuple,
    IncrementRequestedEvent.OutputTuple,
    IncrementRequestedEvent.OutputObject
  >;

  filters: {
    "CounterIncremented(uint256,address)": TypedContractEvent<
      CounterIncrementedEvent.InputTuple,
      CounterIncrementedEvent.OutputTuple,
      CounterIncrementedEvent.OutputObject
    >;
    CounterIncremented: TypedContractEvent<
      CounterIncrementedEvent.InputTuple,
      CounterIncrementedEvent.OutputTuple,
      CounterIncrementedEvent.OutputObject
    >;

    "CounterInitialized(address)": TypedContractEvent<
      CounterInitializedEvent.InputTuple,
      CounterInitializedEvent.OutputTuple,
      CounterInitializedEvent.OutputObject
    >;
    CounterInitialized: TypedContractEvent<
      CounterInitializedEvent.InputTuple,
      CounterInitializedEvent.OutputTuple,
      CounterInitializedEvent.OutputObject
    >;

    "IncrementRequested(uint256,address)": TypedContractEvent<
      IncrementRequestedEvent.InputTuple,
      IncrementRequestedEvent.OutputTuple,
      IncrementRequestedEvent.OutputObject
    >;
    IncrementRequested: TypedContractEvent<
      IncrementRequestedEvent.InputTuple,
      IncrementRequestedEvent.OutputTuple,
      IncrementRequestedEvent.OutputObject
    >;
  };
}
